### ISSUE TITLE
"Content-length" for everest_update.yaml in http header 

### ISSUE THREAD

**Issue by Cooky-12** [maddie480/EverestUpdateCheckerServer#75]
Hi, I'm trying to write a script to download celeste mod.

Thanks for your "everest_update.yaml", I can process mod dependencies.

But I didn't find "Content-length" in everest_update.yaml download response, it may useful to add "Content-length" to help check download is real complete ?

**Comment by maddie480** [comment]
All APIs should now return a Content-Length (well, except the bundle-download one because the zip is written on the fly 😅)

**Comment by Cooky-12** [comment]
Thank you very much ! 😄
